parameters: {}
environment: {}
packages:
    - name: transcode
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: 480p
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          webSecure: false
          parameters: {}
          environment:
            S3_ACCESS_KEY_ID : "${S3_ACCESS_KEY_ID}"
            S3_ACCESS_KEY_SECRET : "${S3_ACCESS_KEY_ID}"
            S3_REGION : "${S3_REGION}"
            S3_ENDPOINT : "${S3_ENDPOINT}"
          annotations: {}
          limits:
            timeout: 900000
            memory: 1024
